server:
  port: 8081
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: R@mee6012
    url: jdbc:mysql://localhost:3306/takeo
    username: root
    
  jpa:
    show-sql: true
        